# Use Node.js 18 LTS Alpine image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY ./automation/package.json ./

# Install dependencies
RUN npm install

# Copy automation code code
COPY ./automation .

RUN npm run build

# Start the service
CMD ["npm", "run", "start"] 